[build]
target = "index.html"
dist = "./static/dist"

[tools]
tailwindcss = " 3.3.2"

[[hooks]]
stage = "post_build"
command = "sh"
command_arguments = ["-c", "cp ./css/main.css $TRUNK_STAGING_DIR/main.css"]
